tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/git"
brew "asciinema"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "dnscontrol"
brew "flarectl"
brew "git"
brew "git-extras"
brew "git-filter-repo"
brew "go"
brew "httpie"
brew "hub"
brew "hugo"
brew "ipcalc"
brew "jq"
brew "mas"
brew "mitmproxy"
brew "mtr"
brew "nmap"
brew "pipx"
brew "poetry"
brew "redis", restart_service: true
brew "the_silver_searcher"
brew "weechat"
brew "wget"
brew "youtube-dl"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "aws-vault"
cask "bettertouchtool"
cask "brave-browser"
cask "caffeine"
cask "daisydisk"
cask "dash"
cask "deckset"
cask "discord"
cask "docker"
cask "dropbox"
cask "force-paste", args: { "no-quarantine": true }
cask "git-credential-manager-core"
cask "gpg-suite"
cask "hex-fiend"
cask "iterm2"
cask "keybase"
cask "keysmith"
cask "licecap"
cask "loopback"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "pdfpen"
cask "rar"
cask "rectangle"
cask "rq"
cask "sequel-ace"
cask "signal"
cask "slack"
cask "soulver"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "transmission"
cask "transmission-remote-gui"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "wireshark"
cask "xquartz"
mas "1Password for Safari", id: 1569813296
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "Paprika Recipe Manager", id: 451907568
mas "Pixelmator Pro", id: 1289583905
mas "Tailscale", id: 1475387142
mas "WireGuard", id: 1451685025
