---
- name: Setup
  hosts: localhost
  tasks:
    - name: Gathering custom facts
      setup:
        fact_path: "facts.d"

    - name: macos
      import_tasks: tasks/macos.yml
    - name: repos
      import_tasks: tasks/repos.yml
    - name: pipx
      import_tasks: tasks/pipx.yml
    - name: vscode
      import_tasks: tasks/vscode.yml
    - name: fastfoward
      import_tasks: tasks/fastforward.yml
