---
- name: Setup
  hosts: localhost
  tasks:
    - name: Gathering custom facts
      setup:
        fact_path: "facts.d"

    - name: Configuring sudo to accept touch ID
      become: true
      lineinfile:
        path: /etc/pam.d/sudo
        insertafter: ^auth
        firstmatch: true
        line: auth       sufficient     pam_tid.so

    - name: repos
      import_tasks: tasks/repos.yml
    - name: pipx
      import_tasks: tasks/pipx.yml
    - name: vscode
      import_tasks: tasks/vscode.yml
    - name: fastfoward
      import_tasks: tasks/fastforward.yml
