- name: Configuring sudo to accept touch ID
  become: true
  lineinfile:
    path: /etc/pam.d/sudo
    insertafter: ^auth
    firstmatch: true
    line: auth       sufficient     pam_tid.so

- name: Adding Homebrew ZSH to acceptable shells
  become: true
  blockinfile:
    path: /etc/shells
    block: |
      /usr/local/bin/zsh
      /opt/homebrew/bin/zsh

- name: Check .netrc permissions
  file:
    path: ~/.netrc
    mode: 0700

- name: Configure default $PATH
  become: true
  copy:
    mode: '0644'
    owner: root
    group: wheel
    src: files/etc/paths
    dest: /etc/paths
